main = mydocument
current = mychapter

YUKITASK_EDITOR ?= $(EDITOR)

all:
	platex $(main).tex
	dvipdfmx $(main).dvi
	open $(main).pdf

e:
	$(YUKITASK_EDITOR) $(current).tex

show:
	open $(main).pdf

main:
	$(YUKITASK_EDITOR) $(main).tex

bk:
	# (pushd ..; zip -r PROJECT-BACKUP.zip PROJECT-DIRNAME; popd)
	@echo You are executing \'bk\' command.  Please edit your \'makefile\'.

# vim: set filetype=make:
